# action.yml
name: 'Build Action'
description: 'Build a useless program and give it a name'
inputs:
  program-name:  # id of input
    description: 'The name of the useless program'
    required: true
    default: 'nothing'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.program-name }}