# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  program-name:  # id of input
    description: 'Program Name'
    required: true
    default: 'appName'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.who-to-greet }}