# action.yml
name: 'Build Action'
description: 'Build a useless program and give it a name'
inputs:
  who-to-greet:  # id of input
    description: Greetings
    required: true
    default: 'no name'
outputs:
  time: # id of output
    description: 'The of the build'
runs:
  using: 'docker'
  image: 'dockerfile'