on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: This job is just a hello world
    steps:
    - uses: actions/checkout@v2

    - name: Hello world action step
      id: hello
      uses: dionisioedu/hello-world-docker-action@v1
      with:
        program-name: 'appDocker'

    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }} .."

  # build-and-test:
  #   runs-on: ubuntu-latest
  #   name: Build And Test
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Build
  #     uses: hello-world-docker-action/action-build-tests@main
  #     with:
  #       program-name: 'myProgram'
